### ISSUE TITLE
Warnings about 'getInitialState' in ES6 component class

### ISSUE THREAD

**Issue by xJkit** [trendmicro-frontend/react-tooltip#1]
React is complaining in console about `getInitialState()` which was used for React.createClass and deprecated in ES6 component class. Rename getInitialState() to `getInitState` or something else may help.

```
Warning: getInitialState was defined on Tooltip, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
```

**Comment by seawind543** [comment]
Fixed by https://github.com/trendmicro-frontend/react-tooltip/commit/098c5c2d892e05b64086ca57ec9a6a9f9e61763e
