### ISSUE TITLE
Tooltip position misplacement on very long texts

### ISSUE THREAD

**Issue by xJkit** [trendmicro-frontend/react-tooltip#3]
Tooltip content window will calculate the width of  text and place on the following 4 positions: top, left, right and bottom. However, on a very long truncated text (or may be hidden by over-flow + text-overflow) the tooltip window will disappear because of the wrong position.

1. Wish to add placements like `top-left` or `bottom-left` to resolve the scenario like that
2. Wish to add placement according to the mouse cursor position. By doing so, it fixes the problem above, too.

**Comment by seawind543** [comment]
v0.4.0
- Support auto adjust placement.
- Separated into Tooltip and Infotip.
-- Infotip support 'rightTop', 'rightBottom', 'leftTop', and 'leftBottom' as Trend Micro HIE's SPEC.
