### ISSUE TITLE
Feature Request: Disable Tooltip Component 

### ISSUE THREAD

**Issue by cheton** [trendmicro-frontend/react-tooltip#4]
Is there an easy way to disable tooltip? For example, I may want to hide tooltip when clicking on the target element, or disable tooltip when a button is disabled. How about using a "disabled" prop to enable/disable tooltip?

**Comment by cheton** [comment]
```js
if (disabled) {
    return this.props.children;
}

return (
    <Trigger>{this.props.children}</Trigger>  
);
```

**Comment by seawind543** [comment]
v0.4.9 had support "disabled" prop to enable/disable tooltip/infotip.
