### ISSUE TITLE
Set Infotip inside RadioGroup will get runtime error

### ISSUE THREAD

**Issue by seawind543** [trendmicro-frontend/react-tooltip#5]
Set Infotip inside RadioGroup will get run time error about "React.Children.only"

https://github.com/trendmicro-frontend/react-radio

```
<RadioGroup
    name="comic"
    value={spywareValue}
    onChange={(value, event) => {
        this.handleSpywareChange(0);
    }}
>
    <RadioButton value="dc:batman">
        Example
        <Infotip content="This is a simple example for infotip.">
            <span className="fa fa-info-circle" />
        </Infotip>
    </RadioButton>
    <RadioButton label="Hulk (Marvel)" value="marvel:hulk" />
</RadioGroup>
```

<img width="557" alt="35244965-a4b6e8d0-ffca-11e7-96d6-716f11903039" src="https://user-images.githubusercontent.com/27720673/35257065-29078ba0-0032-11e8-8bc2-df6787b38ada.png">

**Comment by cheton** [comment]
For me, I would suggest removing the wrapped div from the children, so the trigger can accept children with inline, inline-block, or block attributes.

**Comment by seawind543** [comment]
Agree. Will remove wrapper from next version.

**Comment by seawind543** [comment]
Apply Tooltip v0.4.5 with RadioGroup of react-radio v3.0.0
For react-radio v3.1.0 and later, we could apply Tooltip v0.4.9 (which no longer wrap children with a <div/> element.)
